name: CI/CD pipeline

on: push

jobs:
    ci-cd-pipeline:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Setup Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.10.0
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install build
              python -m pip install flake8
              python -m pip install pytest
              python -m pip install --upgrade twine
          - name: Build binary wheel and a source tarball
            run: python -m build
          - name: Publish distribution to Test PyPI
            uses: python -m twine upload --repository testpypi dist/*
            with:
              password: ${{ secrets.test_pypi_password }}
              repository_url: https://test.pypi.org/legacy/