name: mypy test

on:
  push:
    branches: [ master ]

jobs:
  run_mypy:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Mypy
        uses: jpetrucciani/mypy-check@master
        with:
          path: '.\src\molviewer\'

