name: mypy test

on:
  push:
    branches: [ master ]

jobs:
  run_mypy:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Mypy Check
      uses: jpetrucciani/mypy-check@0.930
      with:
        path: '.\src\molviewer\'
        mypy_flags: '--install-types --non-interactive'
